#include "Compile.h"

namespace rat::cc {
	const String& builtinPredefs() {
		static String cache =
				String("#define _LP64 1\n"
							 "#define _STDC_PREDEF_H 1\n"
							 "#define __ATOMIC_ACQUIRE 2\n"
							 "#define __ATOMIC_ACQ_REL 4\n"
							 "#define __ATOMIC_CONSUME 1\n"
							 "#define __ATOMIC_HLE_ACQUIRE 65536\n"
							 "#define __ATOMIC_HLE_RELEASE 131072\n"
							 "#define __ATOMIC_RELAXED 0\n"
							 "#define __ATOMIC_RELEASE 3\n"
							 "#define __ATOMIC_SEQ_CST 5\n"
							 "#define __BIGGEST_ALIGNMENT__ 16\n"
							 "#define __BYTE_ORDER__ __ORDER_LITTLE_ENDIAN__\n"
							 "#define __CHAR16_TYPE__ short unsigned int\n"
							 "#define __CHAR32_TYPE__ unsigned int\n"
							 "#define __CHAR_BIT__ 8\n"
							 "#define __DBL_DECIMAL_DIG__ 17\n"
							 "#define __DBL_DENORM_MIN__ ((double)4.94065645841246544176568792868221372e-324L)\n"
							 "#define __DBL_DIG__ 15\n"
							 "#define __DBL_EPSILON__ ((double)2.22044604925031308084726333618164062e-16L)\n"
							 "#define __DBL_HAS_DENORM__ 1\n"
							 "#define __DBL_HAS_INFINITY__ 1\n"
							 "#define __DBL_HAS_QUIET_NAN__ 1\n"
							 "#define __DBL_IS_IEC_60559__ 1\n"
							 "#define __DBL_MANT_DIG__ 53\n"
							 "#define __DBL_MAX_10_EXP__ 308\n"
							 "#define __DBL_MAX_EXP__ 1024\n"
							 "#define __DBL_MAX__ ((double)1.79769313486231570814527423731704357e+308L)\n"
							 "#define __DBL_MIN_10_EXP__ (-307)\n"
							 "#define __DBL_MIN_EXP__ (-1021)\n"
							 "#define __DBL_MIN__ ((double)2.22507385850720138309023271733240406e-308L)\n"
							 "#define __DBL_NORM_MAX__ ((double)1.79769313486231570814527423731704357e+308L)\n"
							 "#define __DECIMAL_BID_FORMAT__ 1\n"
							 "#define __DECIMAL_DIG__ 21\n"
							 "#define __ELF__ 1\n"
							 "#define __FINITE_MATH_ONLY__ 0\n"
							 "#define __FLOAT_WORD_ORDER__ __ORDER_LITTLE_ENDIAN__\n"
							 "#define __FLT_DECIMAL_DIG__ 9\n"
							 "#define __FLT_DENORM_MIN__ 1.40129846432481707092372958328991613e-45F\n"
							 "#define __FLT_DIG__ 6\n"
							 "#define __FLT_EPSILON__ 1.19209289550781250000000000000000000e-7F\n"
							 "#define __FLT_EVAL_METHOD_TS_18661_3__ 0\n"
							 "#define __FLT_EVAL_METHOD__ 0\n"
							 "#define __FLT_HAS_DENORM__ 1\n"
							 "#define __FLT_HAS_INFINITY__ 1\n"
							 "#define __FLT_HAS_QUIET_NAN__ 1\n"
							 "#define __FLT_IS_IEC_60559__ 1\n"
							 "#define __FLT_MANT_DIG__ 24\n"
							 "#define __FLT_MAX_10_EXP__ 38\n"
							 "#define __FLT_MAX_EXP__ 128\n"
							 "#define __FLT_MAX__ 3.40282346638528859811704183484516925e+38F\n"
							 "#define __FLT_MIN_10_EXP__ (-37)\n"
							 "#define __FLT_MIN_EXP__ (-125)\n"
							 "#define __FLT_MIN__ 1.17549435082228750796873653722224568e-38F\n"
							 "#define __FLT_NORM_MAX__ 3.40282346638528859811704183484516925e+38F\n"
							 "#define __FLT_RADIX__ 2\n"
							 "#define __FXSR__ 1\n"
							 "#define __GCC_ASM_FLAG_OUTPUTS__ 1\n"
							 "#define __GCC_ATOMIC_BOOL_LOCK_FREE 2\n"
							 "#define __GCC_ATOMIC_CHAR16_T_LOCK_FREE 2\n"
							 "#define __GCC_ATOMIC_CHAR32_T_LOCK_FREE 2\n"
							 "#define __GCC_ATOMIC_CHAR_LOCK_FREE 2\n"
							 "#define __GCC_ATOMIC_INT_LOCK_FREE 2\n"
							 "#define __GCC_ATOMIC_LLONG_LOCK_FREE 2\n"
							 "#define __GCC_ATOMIC_LONG_LOCK_FREE 2\n"
							 "#define __GCC_ATOMIC_POINTER_LOCK_FREE 2\n"
							 "#define __GCC_ATOMIC_SHORT_LOCK_FREE 2\n"
							 "#define __GCC_ATOMIC_TEST_AND_SET_TRUEVAL 1\n"
							 "#define __GCC_ATOMIC_WCHAR_T_LOCK_FREE 2\n"
							 "#define __GCC_CONSTRUCTIVE_SIZE 64\n"
							 "#define __GCC_DESTRUCTIVE_SIZE 64\n"
							 "#define __GCC_HAVE_DWARF2_CFI_ASM 1\n"
							 "#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1 1\n"
							 "#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2 1\n"
							 "#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4 1\n"
							 "#define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8 1\n"
							 "#define __GCC_IEC_559 2\n"
							 "#define __GCC_IEC_559_COMPLEX 2\n"
							 "#define __GNUC_EXECUTION_CHARSET_NAME \"UTF-8\"\n"
							 "#define __GNUC_MINOR__ 3\n"
							 "#define __GNUC_PATCHLEVEL__ 0\n"
							 "#define __GNUC_STDC_INLINE__ 1\n"
							 "#define __GNUC_WIDE_EXECUTION_CHARSET_NAME \"UTF-32LE\"\n"
							 "#define __GNUC__ 13\n"
							 "#define __HAVE_SPECULATION_SAFE_VALUE 1\n"
							 "#define __INT16_C(c) c\n"
							 "#define __INT16_MAX__ 0x7fff\n"
							 "#define __INT16_TYPE__ short int\n"
							 "#define __INT32_C(c) c\n"
							 "#define __INT32_MAX__ 0x7fffffff\n"
							 "#define __INT32_TYPE__ int\n"
							 "#define __INT64_C(c) c ## L\n"
							 "#define __INT64_MAX__ 0x7fffffffffffffffL\n"
							 "#define __INT64_TYPE__ long int\n"
							 "#define __INT8_C(c) c\n"
							 "#define __INT8_MAX__ 0x7f\n"
							 "#define __INT8_TYPE__ signed char\n"
							 "#define __INTMAX_C(c) c ## L\n"
							 "#define __INTMAX_MAX__ 0x7fffffffffffffffL\n"
							 "#define __INTMAX_TYPE__ long int\n"
							 "#define __INTMAX_WIDTH__ 64\n"
							 "#define __INTPTR_MAX__ 0x7fffffffffffffffL\n"
							 "#define __INTPTR_TYPE__ long int\n"
							 "#define __INTPTR_WIDTH__ 64\n"
							 "#define __INT_FAST16_MAX__ 0x7fffffffffffffffL\n"
							 "#define __INT_FAST16_TYPE__ long int\n"
							 "#define __INT_FAST16_WIDTH__ 64\n"
							 "#define __INT_FAST32_MAX__ 0x7fffffffffffffffL\n"
							 "#define __INT_FAST32_TYPE__ long int\n"
							 "#define __INT_FAST32_WIDTH__ 64\n"
							 "#define __INT_FAST64_MAX__ 0x7fffffffffffffffL\n"
							 "#define __INT_FAST64_TYPE__ long int\n"
							 "#define __INT_FAST64_WIDTH__ 64\n"
							 "#define __INT_FAST8_MAX__ 0x7f\n"
							 "#define __INT_FAST8_TYPE__ signed char\n"
							 "#define __INT_FAST8_WIDTH__ 8\n"
							 "#define __INT_LEAST16_MAX__ 0x7fff\n"
							 "#define __INT_LEAST16_TYPE__ short int\n"
							 "#define __INT_LEAST16_WIDTH__ 16\n"
							 "#define __INT_LEAST32_MAX__ 0x7fffffff\n"
							 "#define __INT_LEAST32_TYPE__ int\n"
							 "#define __INT_LEAST32_WIDTH__ 32\n"
							 "#define __INT_LEAST64_MAX__ 0x7fffffffffffffffL\n"
							 "#define __INT_LEAST64_TYPE__ long int\n"
							 "#define __INT_LEAST64_WIDTH__ 64\n"
							 "#define __INT_LEAST8_MAX__ 0x7f\n"
							 "#define __INT_LEAST8_TYPE__ signed char\n"
							 "#define __INT_LEAST8_WIDTH__ 8\n"
							 "#define __INT_MAX__ 0x7fffffff\n"
							 "#define __INT_WIDTH__ 32\n"
							 "#define __LDBL_DECIMAL_DIG__ 21\n"
							 "#define __LDBL_DENORM_MIN__ 3.64519953188247460252840593361941982e-4951L\n"
							 "#define __LDBL_DIG__ 18\n"
							 "#define __LDBL_EPSILON__ 1.08420217248550443400745280086994171e-19L\n"
							 "#define __LDBL_HAS_DENORM__ 1\n"
							 "#define __LDBL_HAS_INFINITY__ 1\n"
							 "#define __LDBL_HAS_QUIET_NAN__ 1\n"
							 "#define __LDBL_IS_IEC_60559__ 1\n"
							 "#define __LDBL_MANT_DIG__ 64\n"
							 "#define __LDBL_MAX_10_EXP__ 4932\n"
							 "#define __LDBL_MAX_EXP__ 16384\n"
							 "#define __LDBL_MAX__ 1.18973149535723176502126385303097021e+4932L\n"
							 "#define __LDBL_MIN_10_EXP__ (-4931)\n"
							 "#define __LDBL_MIN_EXP__ (-16381)\n"
							 "#define __LDBL_MIN__ 3.36210314311209350626267781732175260e-4932L\n"
							 "#define __LDBL_NORM_MAX__ 1.18973149535723176502126385303097021e+4932L\n"
							 "#define __LONG_LONG_MAX__ 0x7fffffffffffffffLL\n"
							 "#define __LONG_LONG_WIDTH__ 64\n"
							 "#define __LONG_MAX__ 0x7fffffffffffffffL\n"
							 "#define __LONG_WIDTH__ 64\n"
							 "#define __LP64__ 1\n"
							 "#define __MMX_WITH_SSE__ 1\n"
							 "#define __MMX__ 1\n"
							 "#define __NO_INLINE__ 1\n"
							 "#define __ORDER_BIG_ENDIAN__ 4321\n"
							 "#define __ORDER_LITTLE_ENDIAN__ 1234\n"
							 "#define __ORDER_PDP_ENDIAN__ 3412\n"
							 "#define __PRAGMA_REDEFINE_EXTNAME 1\n"
							 "#define __PTRDIFF_MAX__ 0x7fffffffffffffffL\n"
							 "#define __PTRDIFF_TYPE__ long int\n"
							 "#define __PTRDIFF_WIDTH__ 64\n"
							 "#define __REGISTER_PREFIX__ \n"
							 "#define __SCHAR_MAX__ 0x7f\n"
							 "#define __SCHAR_WIDTH__ 8\n"
							 "#define __SEG_FS 1\n"
							 "#define __SEG_GS 1\n"
							 "#define __SHRT_MAX__ 0x7fff\n"
							 "#define __SHRT_WIDTH__ 16\n"
							 "#define __SIG_ATOMIC_MAX__ 0x7fffffff\n"
							 "#define __SIG_ATOMIC_MIN__ (-__SIG_ATOMIC_MAX__ - 1)\n"
							 "#define __SIG_ATOMIC_TYPE__ int\n"
							 "#define __SIG_ATOMIC_WIDTH__ 32\n"
							 "#define __SIZEOF_DOUBLE__ 8\n"
							 "#define __SIZEOF_FLOAT128__ 16\n"
							 "#define __SIZEOF_FLOAT80__ 16\n"
							 "#define __SIZEOF_FLOAT__ 4\n"
							 "#define __SIZEOF_INT__ 4\n"
							 "#define __SIZEOF_LONG_DOUBLE__ 16\n"
							 "#define __SIZEOF_LONG_LONG__ 8\n"
							 "#define __SIZEOF_LONG__ 8\n"
							 "#define __SIZEOF_POINTER__ 8\n"
							 "#define __SIZEOF_PTRDIFF_T__ 8\n"
							 "#define __SIZEOF_SHORT__ 2\n"
							 "#define __SIZEOF_SIZE_T__ 8\n"
							 "#define __SIZEOF_WCHAR_T__ 4\n"
							 "#define __SIZEOF_WINT_T__ 4\n"
							 "#define __SIZE_MAX__ 0xffffffffffffffffUL\n"
							 "#define __SIZE_TYPE__ long unsigned int\n"
							 "#define __SIZE_WIDTH__ 64\n"
							 "#define __SSE2_MATH__ 1\n"
							 "#define __SSE2__ 1\n"
							 "#define __SSE_MATH__ 1\n"
							 "#define __SSE__ 1\n"
							 "#define __STDC_HOSTED__ 1\n"
							 "#define __STDC_IEC_559_COMPLEX__ 1\n"
							 "#define __STDC_IEC_559__ 1\n"
							 "#define __STDC_IEC_60559_BFP__ 201404L\n"
							 "#define __STDC_IEC_60559_COMPLEX__ 201404L\n"
							 "#define __STDC_ISO_10646__ 201706L\n"
							 "#define __STDC_UTF_16__ 1\n"
							 "#define __STDC_UTF_32__ 1\n"
							 "#define __STDC_VERSION__ 201112L\n"
							 "#define __STDC__ 1\n"
							 "#define __STRICT_ANSI__ 1\n"
							 "#define __UINT16_C(c) c\n"
							 "#define __UINT16_MAX__ 0xffff\n"
							 "#define __UINT16_TYPE__ short unsigned int\n"
							 "#define __UINT32_C(c) c ## U\n"
							 "#define __UINT32_MAX__ 0xffffffffU\n"
							 "#define __UINT32_TYPE__ unsigned int\n"
							 "#define __UINT64_C(c) c ## UL\n"
							 "#define __UINT64_MAX__ 0xffffffffffffffffUL\n"
							 "#define __UINT64_TYPE__ long unsigned int\n"
							 "#define __UINT8_C(c) c\n"
							 "#define __UINT8_MAX__ 0xff\n"
							 "#define __UINT8_TYPE__ unsigned char\n"
							 "#define __UINTMAX_C(c) c ## UL\n"
							 "#define __UINTMAX_MAX__ 0xffffffffffffffffUL\n"
							 "#define __UINTMAX_TYPE__ long unsigned int\n"
							 "#define __UINTPTR_MAX__ 0xffffffffffffffffUL\n"
							 "#define __UINTPTR_TYPE__ long unsigned int\n"
							 "#define __UINT_FAST16_MAX__ 0xffffffffffffffffUL\n"
							 "#define __UINT_FAST16_TYPE__ long unsigned int\n"
							 "#define __UINT_FAST32_MAX__ 0xffffffffffffffffUL\n"
							 "#define __UINT_FAST32_TYPE__ long unsigned int\n"
							 "#define __UINT_FAST64_MAX__ 0xffffffffffffffffUL\n"
							 "#define __UINT_FAST64_TYPE__ long unsigned int\n"
							 "#define __UINT_FAST8_MAX__ 0xff\n"
							 "#define __UINT_FAST8_TYPE__ unsigned char\n"
							 "#define __UINT_LEAST16_MAX__ 0xffff\n"
							 "#define __UINT_LEAST16_TYPE__ short unsigned int\n"
							 "#define __UINT_LEAST32_MAX__ 0xffffffffU\n"
							 "#define __UINT_LEAST32_TYPE__ unsigned int\n"
							 "#define __UINT_LEAST64_MAX__ 0xffffffffffffffffUL\n"
							 "#define __UINT_LEAST64_TYPE__ long unsigned int\n"
							 "#define __UINT_LEAST8_MAX__ 0xff\n"
							 "#define __UINT_LEAST8_TYPE__ unsigned char\n"
							 "#define __USER_LABEL_PREFIX__ \n"
							 "#define __VERSION__ \"13.3.0\"\n"
							 "#define __WCHAR_MAX__ 0x7fffffff\n"
							 "#define __WCHAR_MIN__ (-__WCHAR_MAX__ - 1)\n"
							 "#define __WCHAR_TYPE__ int\n"
							 "#define __WCHAR_WIDTH__ 32\n"
							 "#define __WINT_MAX__ 0xffffffffU\n"
							 "#define __WINT_MIN__ 0U\n"
							 "#define __WINT_TYPE__ unsigned int\n"
							 "#define __WINT_WIDTH__ 32\n"
							 "#define __amd64 1\n"
							 "#define __amd64__ 1\n"
							 "#define __code_model_small__ 1\n"
							 "#define __gnu_linux__ 1\n"
							 "#define __k8 1\n"
							 "#define __k8__ 1\n"
							 "#define __linux 1\n"
							 "#define __linux__ 1\n"
							 "#define __ratcc__ 1\n"
							 "#define __unix 1\n"
							 "#define __unix__ 1\n"
							 "#define __x86_64 1\n"
							 "#define __x86_64__ 1\n") +
				"\n";
		return cache;
	}
} // namespace rat::cc
